### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by AnyRandomGuy** [tschuy/minecraft-server-control#2]
I have got a few questions:
1. Where should I put this script?
2. How do I set it up?
3. How do I run it?

I've put in the server's folder, ran the script, and got the following error message:

========= RESTART: C:\Users\Brigitte\Desktop\Localhost\minecraft.py =========
Traceback (most recent call last):
  File "C:\Users\Brigitte\Desktop\Localhost\minecraft.py", line 107, in <module>
    main()
  File "C:\Users\Brigitte\Desktop\Localhost\minecraft.py", line 93, in main
    if sys.argv[1] == 'start':
IndexError: list index out of range

**Comment by ImACouch** [comment]
I have the same issue.
